version: '3'
services:
  vicon-driver:
    build:
      context: ./
      args:
        # Change to Vicon server IP address
        vicon_server_ip: 127.0.0.1
    container_name: vicon-driver-c
    tty: true
    image: vicon-driver
    network_mode: "host"
    environment:
      ROS_HOSTNAME: docker-desktop
      ROS_MASTER_URI: http://docker-desktop:11311
